---
title: "Instructions Code"
author: "S Santos"
date: "Thursday, September 18, 2014"
output: html_document
---

<font size="5">

*IMPORTANT: To test code Go straight to step 2 below*

# INSTRUCTIONS 

##  Place all your txt files into ION folder inside Statistics folder. 

## Run the Main code:

Code_2014 inside the Code_2014 in folder, i.e. Force_Dissipation_2014Oct19.m, and choose folder where text files are, i.e. the ION folder inside the Statistics folder.  

* Note for **TEST**: 

- To test the code leave the AFM_1.txt file in and choose the folder ION when you run the code. 

- Choose k=40, Q=500 and f=350000. 

- For Elastic modulus choose 1 otherwise 0. 

- The smoothing factor should go from 0.01 to 0.3, i.e. less to more smoothing. 


## GET Statistic (Conservative part and optional) 

- When the folders are done place folder from ION folder into folder inside it called 20131225 48h (historical reasons!)
 

- Run the FiguresProcessing.m instide Statistics for conservative data in long range:

You will get a matrix, ResulrMat with three columns:

* Fadhesion, i.e. related to chemical affinity and capilarity

* Area under the curve, i.e. work required to separate tip from sample

* The distance IncrFad, i.e. related to the height of water layers

For details on, and definitions of, the meaning of the above parameters check:

- [here](http://scitation.aip.org/content/aip/journal/jcp/139/8/10.1063/1.4819267?showFTTab=true&containerItemId=content/aip/journal/jcp)

Amadei, C. A., Tang, T. C., Chiesa, M. & Santos, S. The aging of a surface and the evolution of conservative and dissipative nanoscale interactions. The Journal of Chemical Physics 139, 084708 (2013).

- There is information on the meaning of the Area under the curve 
[here](http://pubs.acs.org/doi/abs/10.1021/jp411125n)  
  
  
Tang, T.-C., Amadei, C. A., Thomson, N. H. & Chiesa, M. Ion Exchange and DNA Molecular Dip Sticks: Studying the Nanoscale Surface Wetting of Muscovite Mica. Journal of Physical Chemistry C 118, 4695-4701 (2014).

### Extra information on Energy dissipation, Virial and force of Adhesion

In order to see what the mean and standard deiation of the data for the adhesion force, the energy dissipation and the virial (maxima) is run the
file:

AveragesVirial_Edis_Etc.m

The data is stored in the variables **Adhesion_M**, **Edis_crop_M**, 
and **Virial_M**

### **Elastic Modulus**:

Run AveragesElasticity.m inside the Code_2014 folder
This generates statistics also for Elastic Modulus.

You will get a histogram and a box plot. 

</font>